export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const EMPLOYEE_LIST = 'EMPLOYEE_LIST'
export const EMPLOYEE_LEAVE_LIST='EMPLOYEE_LEAVE_LIST'